-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language WebDPConv.

module WebDPConv.Abs where

import Prelude (Double, Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Prog = Program [Query]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Query = Q Ident DatasetId Budget [QueryStep]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data DatasetId = DId Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Budget = PureDP Double | ApproxDP Double Double
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data StringList = Slist [String]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data QueryStep
    = QSelect StringList
    | QRename StringList StringList
    | QFilter StringList
    | QMap String [ColumnSchema]
    | QBin [BinMap]
    | QCnt MParam
    | QMin MParam
    | QMax MParam
    | QSum MParam
    | QMean MParam
    | QGroup [GroupRow]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data GroupRow = GroupRow String [Value]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data DataType
    = BType
    | IType Integer Integer
    | DType Double Double
    | TType
    | EType StringList
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Value = TVal | FVal | IVal Integer | DVal Double | SVal String
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data MParam
    = MParam String NoiseM Budget
    | MParamC String
    | MParamN NoiseM
    | MParamB Budget
    | MParamCN String NoiseM
    | MParamCB String Budget
    | MParamNB NoiseM Budget
    | MParamNull
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data NoiseM = GMech | LMech
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data BinMap = BMap String [Value]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ColumnSchema = CScheme String DataType
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

