-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module WebDPConv.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified WebDPConv.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: WebDPConv.Abs.Ident -> Result
transIdent x = case x of
  WebDPConv.Abs.Ident string -> failure x

transProg :: WebDPConv.Abs.Prog -> Result
transProg x = case x of
  WebDPConv.Abs.Program querys -> failure x

transQuery :: WebDPConv.Abs.Query -> Result
transQuery x = case x of
  WebDPConv.Abs.Q ident datasetid budget querysteps -> failure x

transDatasetId :: WebDPConv.Abs.DatasetId -> Result
transDatasetId x = case x of
  WebDPConv.Abs.DId integer -> failure x

transBudget :: WebDPConv.Abs.Budget -> Result
transBudget x = case x of
  WebDPConv.Abs.PureDP double -> failure x
  WebDPConv.Abs.ApproxDP double1 double2 -> failure x

transStringList :: WebDPConv.Abs.StringList -> Result
transStringList x = case x of
  WebDPConv.Abs.Slist strings -> failure x

transQueryStep :: WebDPConv.Abs.QueryStep -> Result
transQueryStep x = case x of
  WebDPConv.Abs.QSelect stringlist -> failure x
  WebDPConv.Abs.QRename stringlist1 stringlist2 -> failure x
  WebDPConv.Abs.QFilter stringlist -> failure x
  WebDPConv.Abs.QMap string columnschemas -> failure x
  WebDPConv.Abs.QBin binmaps -> failure x
  WebDPConv.Abs.QCnt mparam -> failure x
  WebDPConv.Abs.QMin mparam -> failure x
  WebDPConv.Abs.QMax mparam -> failure x
  WebDPConv.Abs.QSum mparam -> failure x
  WebDPConv.Abs.QMean mparam -> failure x
  WebDPConv.Abs.QGroup grouprows -> failure x

transGroupRow :: WebDPConv.Abs.GroupRow -> Result
transGroupRow x = case x of
  WebDPConv.Abs.GroupRow string values -> failure x

transDataType :: WebDPConv.Abs.DataType -> Result
transDataType x = case x of
  WebDPConv.Abs.BType -> failure x
  WebDPConv.Abs.IType integer1 integer2 -> failure x
  WebDPConv.Abs.DType double1 double2 -> failure x
  WebDPConv.Abs.TType -> failure x
  WebDPConv.Abs.EType stringlist -> failure x

transValue :: WebDPConv.Abs.Value -> Result
transValue x = case x of
  WebDPConv.Abs.TVal -> failure x
  WebDPConv.Abs.FVal -> failure x
  WebDPConv.Abs.IVal integer -> failure x
  WebDPConv.Abs.DVal double -> failure x
  WebDPConv.Abs.SVal string -> failure x

transMParam :: WebDPConv.Abs.MParam -> Result
transMParam x = case x of
  WebDPConv.Abs.MParam string noisem budget -> failure x
  WebDPConv.Abs.MParamC string -> failure x
  WebDPConv.Abs.MParamN noisem -> failure x
  WebDPConv.Abs.MParamB budget -> failure x
  WebDPConv.Abs.MParamCN string noisem -> failure x
  WebDPConv.Abs.MParamCB string budget -> failure x
  WebDPConv.Abs.MParamNB noisem budget -> failure x
  WebDPConv.Abs.MParamNull -> failure x

transNoiseM :: WebDPConv.Abs.NoiseM -> Result
transNoiseM x = case x of
  WebDPConv.Abs.GMech -> failure x
  WebDPConv.Abs.LMech -> failure x

transBinMap :: WebDPConv.Abs.BinMap -> Result
transBinMap x = case x of
  WebDPConv.Abs.BMap string values -> failure x

transColumnSchema :: WebDPConv.Abs.ColumnSchema -> Result
transColumnSchema x = case x of
  WebDPConv.Abs.CScheme string datatype -> failure x
